name: Eveline
favicon: null
layout_spectrum: 0.8658082822803408
typography_spectrum: 0.39650912466458976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1595341933425516
  lightness: 0.5168756146449596
  saturation: 0.3539797125849873
  rhythmicContrast: 0.4225455892737955
purpose: []
